[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL,MOCK_TEST_PRICE,SUBSCRIPTION_PRICE,JOB_POST_PRICE"

[[plugins]]
package = "@netlify/plugin-nextjs"
